### ISSUE TITLE
Slight inconsistency between callback and streams API

### ISSUE THREAD

**Issue by silverwind** [thlorenz/readdirp#23]
The callback API includes directories even with `entryType` unset, while the stream API does not.

**Comment by silverwind** [comment]
Also, the callback API returns `{directories: [], files: []}`which is also not in line with the streams API.

**Comment by thlorenz** [comment]
So what change would actually fix your issue(s)?
I'm unclear on the action item here.

FWIW the result objects provided via streams or callback API should be as similar as possible or ideally have the same properties.

**Comment by silverwind** [comment]
As a first step, I'd make the callback API emit only files with `entryType` undefined.

A second step would be to return just an array in the callback API instead of above object. That would be a semver major. (User can still discern files and folders through `stat.isDirectory`).

**Comment by silverwind** [comment]
Or you go the other route and change the default for both streams and callback to 'all'. My use case definitly needs directories too.

**Comment by thlorenz** [comment]
I'm totally unclear how you get different types using streams vs. callbacks.
[As you can see](https://github.com/thlorenz/readdirp/blob/master/readdirp.js#L54-L55) when using streams it just changes the callback to be push the same data into the stream it would have called back with.

Also this is the first time someone points this out. Could someone else please confirm this problem or could we add a test that fails due to these API differences?

**Comment by silverwind** [comment]
Haven't read the whole source yet, but I think the difference is on the final allProcessed call. I assume this one is for streams:

https://github.com/thlorenz/readdirp/blob/82caf226eeafec8669c604f71e46e5e83c48cc86/readdirp.js#L194

And this one for callback (at least that's what I get):

https://github.com/thlorenz/readdirp/blob/82caf226eeafec8669c604f71e46e5e83c48cc86/readdirp.js#L278

`readdirResult` is the mentioned object with `files` and `directories`.

**Comment by silverwind** [comment]
Maybe `readdirResult` was never meant to be exposed directly?

**Comment by silverwind** [comment]
Simple test:

````
$ mkdir empty-dir && node -e "require('readdirp')({root: 'empty-dir'},console.log)"
null { directories: [], files: [] }
````

**Comment by thlorenz** [comment]
I have no idea what you expect to happen here. You are only giving the last callback and it correctly reports no error and no dirs or files inside empty-dir.

```
node -e "require('readdirp')({root: 'empty-dir'}).on('data', console.log)"
```
never fires because no dirs or files were found which is also correct.

Please write a test that fails demonstrating a bug and we can figure out how to fix it. At this point I'm not convinced there is a bug.

**Comment by es128** [comment]
I don't interpret this thread as describing a bug, more like expressing an opinion about the current API design. I haven't looked closely enough to determine whether I agree with @silverwind's point, but either way I don't see what there is to be gained by making a breaking change at this point. Perhaps to appease the OCD segment of this module's user base. 

As it is, readdirp does its job well, the behavior is deterministic, and it's unlikely any given project is going to use both the stream and callback apis together. Is there a practical reason for messing with it?

**Comment by silverwind** [comment]
Let's see if this is clearer:

- On the streams API, if I pass no options except `root`, I get `data` events with *just* file entries (no directories).

- On the callback API, if I pass no optiones except `root`, I get both files and directories, sorted into arrays of the result object.

I'd have expected that the result collection of the callback API ist just an `array`, with no directories. It's really an minor issue, just something that surprised me.

**Comment by thlorenz** [comment]
Clear enough, thanks @silverwind. Empty array makes no sense in streams API since we only invoke the `'data'` handler when we find an entry.
So not worth changing anything here. Please close if this is ok with you.
Thanks.

**Comment by silverwind** [comment]
The streams API is fine. My propsal was to change the callback API to return a single array instead of this undocumented object format.

But whatever, I see you're not interested in changing any of the API :(

**Comment by es128** [comment]
If the docs are unclear or inaccurate about the behavior we could make an update there. I'll take a look at it later.

**Comment by silverwind** [comment]
Please do! the docs just state an 'collection of entries', which is pretty ambiguous.

**Comment by thlorenz** [comment]
Actually I still don't get it. We consistently return an object with files and directories.
If none were found both are empty arrays.
The same is true if we find files and/or directories [i.e. in this test](https://github.com/thlorenz/readdirp#allprocessed).

So what you are asking to just return an array would actually be inconsistent.
I'm therefore not sure what we could change in the docs.

**Comment by silverwind** [comment]
I mean on the stream API, you get an single `entry` per `data` event. If you want to discern directories from files you have to call `entry.stat.isDirectory()`. On the callback API, I get these two sorted into arrays of their type.

Also, I did a quick test and it seems that the callback API actually ignores the `entryType` option completely, and will always return both directories and files.
