### ISSUE TITLE
Update graceful-fs dependency to 4.x

### ISSUE THREAD

**Issue by bpasero** [thlorenz/readdirp#25]
Can you please update to graceful-fs 4.x? Only that release is working with io.js and so should readdirp.

**Comment by thlorenz** [comment]
Thanks for the tip, fixed with 1ab454e6f0d408a652db2a4a0c1d98aaf03ff5d9.
Also now running tests against io.js as well 592f46ee337416d04a86434b9298762db28035c3.

Published as 1.4.

**Comment by bpasero** [comment]
Thanks!
