### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by vanthome** [thlorenz/readdirp#30]
Hi,
a great lib, but a changelog especially for upgrading to version 2.0.0 would be highly welcomed!
thx

**Comment by es128** [comment]
There were no API changes in the 2.0.0 publish, only dependency updates. Agree that we should start adding release notes - probably to the github releases tab.

https://github.com/thlorenz/readdirp/pull/27#issuecomment-134722800

**Comment by es128** [comment]
I've made an entry for v2.0.0, and will strive to do so for any future releases. Closing the issue.
