### ISSUE TITLE
Sorted results

### ISSUE THREAD

**Issue by felicienfrancois** [thlorenz/readdirp#34]
For now files seems not sorted at all (maybe default OS sort) and order may changes unconsistently (may be due to the trully async mode).

Some operation may require sorted sequential callbacks.

Implementing it outside of readdirp (as a further operation in the final callback) means waiting for full tree walk to start getting results and is not 100% trivial (Because files need to be stored and then sorted per parent directory)

A way to specify __sort property__ and __sort order__ in readdirp would be useful.

**Comment by thlorenz** [comment]
Not what it's supposed to do. Let's not bloat this module, instead write another module that does the sorting. If it has to it could wrap readdirp even though you could just feed readdirp output to it.
