### ISSUE TITLE
Rule for directoryFilter doesn't work as expected

### ISSUE THREAD

**Issue by davej** [thlorenz/readdirp#36]
I tried passing the option:
```js
{ directoryFilter: "!node_modules/!(babel-polyfill)" }
```
My expectation was that this would read the `node_modules/babel-polyfill` directory but filter out everything else from `node_modules`. But the rule ended up filtering nothing.

**Comment by thlorenz** [comment]
That's not how it works .. if that needs to change you need to file an issue with minimatch.
