### ISSUE TITLE
Sort order of recursive results is inconsistent

### ISSUE THREAD

**Issue by bmiller59** [thlorenz/readdirp#40]
I use readdirp because it has a streaming interface, which is really nice. 

In my application I need to match the readdirp stream against a sorted stream of records from a database. (I do this in order to verify that a user has matching permissions to those set in the database for a given file.)

I have encountered a problem in which the matching is failing because the sort order of readdirp's results is inconsistent. 

Is it possible to produce reliably sorted results with current readdirp options? If not, how would I need to extend readdirp to enable such a sorting? I would be happy to submit a pull request if provided some guidance on the best solution.

Thank you.

For reference, three results sets received below:

Run #1:
/server/controllers/photos.js
/server/controllers/status.js
/server/controllers/users.js
/server/models/country.js
/server/models/file.js
/server/models/group.js
/server/models/index.js
/server/models/package.js
/server/models/photo.js
/server/models/role.js
/server/models/user.js
/server/for-client/index.js
/server/modules/limiter.js
/server/modules/msgs.js
/server/modules/schema.js
/server/modules/util.js
/server/routes/adfs.js
/server/routes/admin.js
/server/routes/api.js
/server/routes/files.js
/server/routes/groups.js
/server/routes/home.js
/server/routes/index.js

Run #2:
/server/controllers/photos.js
/server/controllers/status.js
/server/controllers/users.js
/server/models/country.js
/server/models/file.js
/server/models/group.js
/server/models/index.js
/server/models/package.js
/server/models/photo.js
/server/models/role.js
/server/models/user.js
/server/modules/limiter.js
/server/modules/msgs.js
/server/modules/schema.js
/server/modules/util.js
/server/routes/adfs.js
/server/routes/admin.js
/server/routes/api.js
/server/routes/files.js
/server/routes/groups.js
/server/routes/home.js
/server/routes/index.js

Run #3:
/server/controllers/photos.js
/server/controllers/status.js
/server/controllers/users.js
/server/config/.DS_Store
/server/config/config.js
/server/config/couch-session.js
/server/config/db.js
/server/config/express.js
/server/config/multipart.js
/server/config/nginx.js
/server/for-client/index.js
/server/models/country.js
/server/models/file.js
/server/models/group.js
/server/models/index.js
/server/models/package.js
/server/models/photo.js
/server/models/role.js
/server/models/user.js
/server/modules/limiter.js
/server/modules/msgs.js
/server/modules/schema.js
/server/modules/util.js
/server/views/admin.hbs
/server/views/error.hbs
/server/views/index.hbs
/server/views/notify.hbs
/server/views/pwReset.hbs
/server/routes/adfs.js
/server/routes/admin.js
/server/routes/api.js
/server/routes/files.js
/server/routes/groups.js
/server/routes/home.js
/server/routes/index.js

**Comment by yoshuawuyts** [comment]
Can't you sort the results after they've been returned?

**Comment by bmiller59** [comment]
No, this whole application is written in a streamed, functional programming style. I never do a toArray type function. Each item is processed and sent on to the client side individually in a stream.

**Comment by es128** [comment]
I think readdirp might have the same problem with consistent sorting that you do - a lot of the benefits of the streaming may be lost if you buffer up the results in order to sort them. If you need this, I think it's something you'll have to do on your side.

**Comment by bmiller59** [comment]
Thanks. If that's the consensus then that's what I'll do. But before I give up, what if there were a feature that sequenced all of the directory read operations, doing only one at a time. This would preserve the sort order (in exchange for loss of speed) and also address this other issue raised: https://github.com/thlorenz/readdirp/issues/35. 

Would there be support for that?

**Comment by es128** [comment]
@bmiller59 you may want to take a look at https://github.com/kmalakoff/readdirp-walk and its concurrency option

**Comment by bmiller59** [comment]
Thank you for the suggestion. That seems like it could work. In my case I will stick with readdirp as it is a more highly used module and readdirp-walk does not come with streaming built in.

 I will sort readdirp results (using highland.js sortBy function) before matching and streaming to the user.
