### ISSUE TITLE
Option for case-insensitive filter

### ISSUE THREAD

**Issue by ECP-Black** [thlorenz/readdirp#47]
Hello,

is it possible to add a flag for case sensitivity file filter? In minimatch there is an optionflag for that:
https://github.com/isaacs/minimatch#nocase

Currently the filterFilter only matches case sensensitiv.

Kind regards,
Dennis

**Comment by es128** [comment]
You can set filter to be a function, then do your own call to minimatch with whatever options you like. 

This lib does not currently provide a way to pass arbitrary options to minimatch.
